basePath: /v1
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: RESTful API for a social media platform example
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Social API
paths: {}
securityDefinitions:
  ApiKeyAuth:
    description: Type (Bearer) followed by the token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
